apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/full
  - controller-manager
  - numaflow-server

images:
  - name: quay.io/numaproj/numaflow
    newTag: v0.9.2

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: numaflow-controller
    spec:
      template:
        spec:
          containers:
            - name: controller-manager
              env:
                - name: NUMAFLOW_IMAGE
                  value: quay.io/numaproj/numaflow:v0.9.2
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: numaflow-server
    spec:
      template:
        spec:
          containers:
            - name: main
              image: quay.io/numaproj/numaflow:latest
              args: 
              - "server"

